# .readthedocs.yml

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      - pip install poetry==1.8.2
    post_install:
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry -C packages/ni.measurements.metadata.v1.proto install --only main,docs

sphinx:
  configuration: packages/ni.measurements.metadata.v1.proto/docs/conf.py