@startuml dependency-graph
!theme plain

package "Base" {
  [ni.protobuf.types]
  [ni-grpc-extensions]
}

package "Proto Packages" {
  [ni.datamonikers.v1.proto]
  [ni.measurements.data.v1.proto]
}

package "Client Packages" {
  [ni.datamonikers.v1.client]
  [ni.measurements.data.v1.client]
}

[ni.datamonikers.v1.client] --> [ni.datamonikers.v1.proto]
[ni.datamonikers.v1.client] --> [ni-grpc-extensions]
[ni.datamonikers.v1.proto] --> [ni.protobuf.types]

@enduml