# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ni/protobuf/types/vector.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'ni/protobuf/types/vector.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ni.protobuf.types import attribute_value_pb2 as ni_dot_protobuf_dot_types_dot_attribute__value__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eni/protobuf/types/vector.proto\x12\x11ni.protobuf.types\x1a\'ni/protobuf/types/attribute_value.proto\"\x95\x04\n\x06Vector\x12=\n\nattributes\x18\x01 \x03(\x0b\x32).ni.protobuf.types.Vector.AttributesEntry\x12=\n\x0c\x64ouble_array\x18\x02 \x01(\x0b\x32%.ni.protobuf.types.Vector.DoubleArrayH\x00\x12;\n\x0bint32_array\x18\x03 \x01(\x0b\x32$.ni.protobuf.types.Vector.Int32ArrayH\x00\x12\x39\n\nbool_array\x18\x04 \x01(\x0b\x32#.ni.protobuf.types.Vector.BoolArrayH\x00\x12=\n\x0cstring_array\x18\x05 \x01(\x0b\x32%.ni.protobuf.types.Vector.StringArrayH\x00\x1a\x1d\n\x0b\x44oubleArray\x12\x0e\n\x06values\x18\x01 \x03(\x01\x1a\x1c\n\nInt32Array\x12\x0e\n\x06values\x18\x01 \x03(\x05\x1a\x1b\n\tBoolArray\x12\x0e\n\x06values\x18\x01 \x03(\x08\x1a\x1d\n\x0bStringArray\x12\x0e\n\x06values\x18\x01 \x03(\t\x1aT\n\x0f\x41ttributesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x30\n\x05value\x18\x02 \x01(\x0b\x32!.ni.protobuf.types.AttributeValue:\x02\x38\x01\x42\x07\n\x05valueB\x83\x01\n\x15\x63om.ni.protobuf.typesB\x0bVectorProtoP\x01Z\x05types\xa2\x02\x04NIPT\xaa\x02\"NationalInstruments.Protobuf.Types\xca\x02\x11NI\\PROTOBUF\\TYPES\xea\x02\x13NI::Protobuf::Typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ni.protobuf.types.vector_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025com.ni.protobuf.typesB\013VectorProtoP\001Z\005types\242\002\004NIPT\252\002\"NationalInstruments.Protobuf.Types\312\002\021NI\\PROTOBUF\\TYPES\352\002\023NI::Protobuf::Types'
  _globals['_VECTOR_ATTRIBUTESENTRY']._loaded_options = None
  _globals['_VECTOR_ATTRIBUTESENTRY']._serialized_options = b'8\001'
  _globals['_VECTOR']._serialized_start=95
  _globals['_VECTOR']._serialized_end=628
  _globals['_VECTOR_DOUBLEARRAY']._serialized_start=414
  _globals['_VECTOR_DOUBLEARRAY']._serialized_end=443
  _globals['_VECTOR_INT32ARRAY']._serialized_start=445
  _globals['_VECTOR_INT32ARRAY']._serialized_end=473
  _globals['_VECTOR_BOOLARRAY']._serialized_start=475
  _globals['_VECTOR_BOOLARRAY']._serialized_end=502
  _globals['_VECTOR_STRINGARRAY']._serialized_start=504
  _globals['_VECTOR_STRINGARRAY']._serialized_end=533
  _globals['_VECTOR_ATTRIBUTESENTRY']._serialized_start=535
  _globals['_VECTOR_ATTRIBUTESENTRY']._serialized_end=619
# @@protoc_insertion_point(module_scope)
