# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ni/protobuf/types/vector_wrappers.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ni.protobuf.types import vector_pb2 as ni_dot_protobuf_dot_types_dot_vector__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'ni/protobuf/types/vector_wrappers.proto\x12\x11ni.protobuf.types\x1a\x1eni/protobuf/types/vector.proto\">\n\x10VectorArrayValue\x12*\n\x07vectors\x18\x01 \x03(\x0b\x32\x19.ni.protobuf.types.VectorB\x8b\x01\n\x15\x63om.ni.protobuf.typesB\x13VectorWrappersProtoP\x01Z\x05types\xa2\x02\x04NIPT\xaa\x02\"NationalInstruments.Protobuf.Types\xca\x02\x11NI\\PROTOBUF\\TYPES\xea\x02\x13NI::Protobuf::Typesb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ni.protobuf.types.vector_wrappers_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\025com.ni.protobuf.typesB\023VectorWrappersProtoP\001Z\005types\242\002\004NIPT\252\002\"NationalInstruments.Protobuf.Types\312\002\021NI\\PROTOBUF\\TYPES\352\002\023NI::Protobuf::Types'
  _VECTORARRAYVALUE._serialized_start=94
  _VECTORARRAYVALUE._serialized_end=156
# @@protoc_insertion_point(module_scope)
