"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
---------------------------------------------------------------------
---------------------------------------------------------------------
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import ni.protobuf.types.vector_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class VectorArrayValue(google.protobuf.message.Message):
    """An array of vectors."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VECTORS_FIELD_NUMBER: builtins.int
    @property
    def vectors(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[ni.protobuf.types.vector_pb2.Vector]: ...
    def __init__(
        self,
        *,
        vectors: collections.abc.Iterable[ni.protobuf.types.vector_pb2.Vector] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["vectors", b"vectors"]) -> None: ...

global___VectorArrayValue = VectorArrayValue
