# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ni/protobuf/types/xydata_wrappers.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ni.protobuf.types import xydata_pb2 as ni_dot_protobuf_dot_types_dot_xydata__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'ni/protobuf/types/xydata_wrappers.proto\x12\x11ni.protobuf.types\x1a\x1eni/protobuf/types/xydata.proto\"K\n\x16\x44oubleXYDataArrayValue\x12\x31\n\x08x_y_data\x18\x01 \x03(\x0b\x32\x1f.ni.protobuf.types.DoubleXYDataB\x8b\x01\n\x15\x63om.ni.protobuf.typesB\x13XYDataWrappersProtoP\x01Z\x05types\xa2\x02\x04NIPT\xaa\x02\"NationalInstruments.Protobuf.Types\xca\x02\x11NI\\PROTOBUF\\TYPES\xea\x02\x13NI::Protobuf::Typesb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ni.protobuf.types.xydata_wrappers_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\025com.ni.protobuf.typesB\023XYDataWrappersProtoP\001Z\005types\242\002\004NIPT\252\002\"NationalInstruments.Protobuf.Types\312\002\021NI\\PROTOBUF\\TYPES\352\002\023NI::Protobuf::Types'
  _DOUBLEXYDATAARRAYVALUE._serialized_start=94
  _DOUBLEXYDATAARRAYVALUE._serialized_end=169
# @@protoc_insertion_point(module_scope)
