"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
---------------------------------------------------------------------
---------------------------------------------------------------------
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import ni.protobuf.types.xydata_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class DoubleXYDataArrayValue(google.protobuf.message.Message):
    """An array of XY data sets."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    X_Y_DATA_FIELD_NUMBER: builtins.int
    @property
    def x_y_data(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[ni.protobuf.types.xydata_pb2.DoubleXYData]: ...
    def __init__(
        self,
        *,
        x_y_data: collections.abc.Iterable[ni.protobuf.types.xydata_pb2.DoubleXYData] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["x_y_data", b"x_y_data"]) -> None: ...

global___DoubleXYDataArrayValue = DoubleXYDataArrayValue
