name: 'Run and upload unit tests'
description: 'Run unit tests using pytest and upload the results as an artifact.'
inputs:
  package-name:
    description: 'The name of the package to run tests for.'
    required: true
  package-basepath:
    description: 'Relative path to the parent directory of the package.'
    required: false
    default: 'packages'
runs:
  using: "composite"
  steps:
    - name: Get OS version
      run: echo "osVersion=$ImageOS" >> "$GITHUB_ENV"
      shell: bash
    - name: Cache ${{ inputs.package-name }} virtualenv
      uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
      with:
        path: ${{ github.workspace }}/${{ inputs.package-basepath }}/${{ inputs.package-name }}/.venv
        key: ${{ inputs.package-name }}-${{ runner.os }}-py${{ env.pythonVersion }}-${{ hashFiles(format('{0}/{1}/poetry.lock', inputs.package-basepath, inputs.package-name)) }}
    - name: Install ${{ inputs.package-name }}
      run: poetry install -v
      working-directory: ${{ github.workspace }}/${{ inputs.package-basepath }}/${{ inputs.package-name }}
      shell: bash
    - name: Run ${{ inputs.package-name }} unit tests and code coverage
      run: poetry run pytest ./tests/unit -v --cov=${{ inputs.package-name }} --junitxml=test_results/${{ inputs.package-name }}-${{ env.osVersion }}-py${{ env.pythonVersion }}.xml
      working-directory: ${{ github.workspace }}/${{ inputs.package-basepath }}/${{ inputs.package-name }}
      shell: bash
    - name: Upload ${{ inputs.package-name }} test results
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      with:
        name: test_results_unit_${{ inputs.package-name }}_${{ env.osVersion }}_py${{ env.pythonVersion }}
        path: ${{ github.workspace }}/${{ inputs.package-basepath }}/${{ inputs.package-name }}/test_results/*.xml
      if: always()
