[tool.poetry]
name = "ni-protobuf-types"
version = "0.1.0"
description = ""
authors = ["Joe Friedrichsen <114173023+jfriedri-ni@users.noreply.github.com>"]
readme = "README.md"
packages = [{include = "ni", from = "src"}]

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
