name: Run unit tests
description: 'Run unit tests for a specific package'

inputs:
  package-name:
    description: 'The name of the package folder to check.'
    default: ''
    required: true
    type: string
  package-basepath:
    description: 'The base path of the package to check, relative to the repo root.'
    default: ''
    required: true
    type: string
  python-version:
    description: 'The version of Python to use'
    default: ''
    required: true
    type: string

runs:
  using: 'composite'
  steps:
    - name: Check out repo
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        submodules: true
    - name: Set up Python
      uses: ni/python-actions/setup-python@8554e7ef74e95c9762962205f45a1e10c48de671 # v0.5.1
      id: setup-python
      with:
        python-version: ${{ inputs.python-version }}
    - name: Set up Poetry
      uses: ni/python-actions/setup-poetry@8554e7ef74e95c9762962205f45a1e10c48de671 # v0.5.1
    - name: Run and upload unit tests for ${{ inputs.package-name }}
      uses: ./.github/actions/run_and_upload_unit_tests
      with:
        package-name: ${{ inputs.package-name }}
        package-basepath: ${{ inputs.package-basepath }}
      working-directory: ${{ github.workspace }}/${{ inputs.package-basepath }}/${{ inputs.package-name }}
