# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ni.datamonikers.v1 import data_moniker_pb2 as ni_dot_datamonikers_dot_v1_dot_data__moniker__pb2


class MonikerServiceStub(object):
    """Service for reading and writing data values using data monikers.

    Not all implementations implement all RPCs and clients should
    handle this gracefully.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BeginSidebandStream = channel.unary_unary(
                '/ni.datamonikers.v1.MonikerService/BeginSidebandStream',
                request_serializer=ni_dot_datamonikers_dot_v1_dot_data__moniker__pb2.BeginMonikerSidebandStreamRequest.SerializeToString,
                response_deserializer=ni_dot_datamonikers_dot_v1_dot_data__moniker__pb2.BeginMonikerSidebandStreamResponse.FromString,
                )
        self.StreamRead = channel.unary_stream(
                '/ni.datamonikers.v1.MonikerService/StreamRead',
                request_serializer=ni_dot_datamonikers_dot_v1_dot_data__moniker__pb2.MonikerList.SerializeToString,
                response_deserializer=ni_dot_datamonikers_dot_v1_dot_data__moniker__pb2.MonikerReadResult.FromString,
                )
        self.StreamWrite = channel.stream_stream(
                '/ni.datamonikers.v1.MonikerService/StreamWrite',
                request_serializer=ni_dot_datamonikers_dot_v1_dot_data__moniker__pb2.MonikerWriteRequest.SerializeToString,
                response_deserializer=ni_dot_datamonikers_dot_v1_dot_data__moniker__pb2.StreamWriteResponse.FromString,
                )
        self.StreamReadWrite = channel.stream_stream(
                '/ni.datamonikers.v1.MonikerService/StreamReadWrite',
                request_serializer=ni_dot_datamonikers_dot_v1_dot_data__moniker__pb2.MonikerWriteRequest.SerializeToString,
                response_deserializer=ni_dot_datamonikers_dot_v1_dot_data__moniker__pb2.MonikerReadResult.FromString,
                )
        self.ReadFromMoniker = channel.unary_unary(
                '/ni.datamonikers.v1.MonikerService/ReadFromMoniker',
                request_serializer=ni_dot_datamonikers_dot_v1_dot_data__moniker__pb2.Moniker.SerializeToString,
                response_deserializer=ni_dot_datamonikers_dot_v1_dot_data__moniker__pb2.ReadFromMonikerResult.FromString,
                )
        self.WriteToMoniker = channel.unary_unary(
                '/ni.datamonikers.v1.MonikerService/WriteToMoniker',
                request_serializer=ni_dot_datamonikers_dot_v1_dot_data__moniker__pb2.WriteToMonikerRequest.SerializeToString,
                response_deserializer=ni_dot_datamonikers_dot_v1_dot_data__moniker__pb2.WriteToMonikerResponse.FromString,
                )


class MonikerServiceServicer(object):
    """Service for reading and writing data values using data monikers.

    Not all implementations implement all RPCs and clients should
    handle this gracefully.
    """

    def BeginSidebandStream(self, request, context):
        """Negotiates a sideband transport for the specified monikers.

        Use this RPC when higher throughput or lower latency are required
        beyond what is traditionally possible with the standard gRPC transport.
        The client supplies the preferred strategy and the list of monikers.
        The server responds with the selected strategy plus the connection
        metadata needed to establish the sideband channel. After this call,
        the actual data exchange is expected to happen over the selected
        sideband transport, not over this unary RPC.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamRead(self, request, context):
        """Subscribes to updates from the requested monikers.

        A response message is returned once a data value is available from
        each read moniker. The order of data values returned matches the order
        of the read monikers. The semantics for when data is published and how
        updates are triggered is implementation dependent.

        Status codes for errors:

        - NOT_FOUND: Specified moniker does not exist
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamWrite(self, request_iterator, context):
        """Streams values to one or more monikers.

        The first request message specifies the write monikers that will be updated.
        Subsequent request messages supply new data values to be written to the
        monikers. The number of data values in each request message must match the
        number of monikers supplied in the original request. The data values are
        applied in order and are paired positionally with the monikers declared in
        the first message. Implementations may choose to return a response message
        after each request has been processed for flow control purposes or no
        response message at all.

        Status codes for errors:

        - NOT_FOUND: Specified moniker does not exist
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamReadWrite(self, request_iterator, context):
        """Streams data to and from the specified read and write monikers.

        The first request message is used to setup the stream and specifies the
        monikers that are to be read and written. No response message is sent for
        the first request message.

        The second and subsequent request messages carry new data values to be written
        to the write monikers similar to the StreamWrite RPC. For each of these request
        message, a response message is returned containing data values from the read
        monikers similar to the StreamRead RPC. Write monikers are always updated before
        data is read from the read monikers.Communication continues in this ping-pong
        fashion until the stream is closed.

        Status codes for errors:

        - NOT_FOUND: Specified moniker does not exist
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadFromMoniker(self, request, context):
        """Reads the current value for a single moniker.

        If no data value is available, implementations may choose to return an empty
        response or return an error.

        Status codes for errors:

        - NOT_FOUND: Specified moniker does not exist
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteToMoniker(self, request, context):
        """Writes a single value to a single moniker.

        Status codes for errors:

        - NOT_FOUND: Specified moniker does not exist
        - INVALID_ARGUMENT: Data type of the data value is not compatible with the moniker
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MonikerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BeginSidebandStream': grpc.unary_unary_rpc_method_handler(
                    servicer.BeginSidebandStream,
                    request_deserializer=ni_dot_datamonikers_dot_v1_dot_data__moniker__pb2.BeginMonikerSidebandStreamRequest.FromString,
                    response_serializer=ni_dot_datamonikers_dot_v1_dot_data__moniker__pb2.BeginMonikerSidebandStreamResponse.SerializeToString,
            ),
            'StreamRead': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamRead,
                    request_deserializer=ni_dot_datamonikers_dot_v1_dot_data__moniker__pb2.MonikerList.FromString,
                    response_serializer=ni_dot_datamonikers_dot_v1_dot_data__moniker__pb2.MonikerReadResult.SerializeToString,
            ),
            'StreamWrite': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamWrite,
                    request_deserializer=ni_dot_datamonikers_dot_v1_dot_data__moniker__pb2.MonikerWriteRequest.FromString,
                    response_serializer=ni_dot_datamonikers_dot_v1_dot_data__moniker__pb2.StreamWriteResponse.SerializeToString,
            ),
            'StreamReadWrite': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamReadWrite,
                    request_deserializer=ni_dot_datamonikers_dot_v1_dot_data__moniker__pb2.MonikerWriteRequest.FromString,
                    response_serializer=ni_dot_datamonikers_dot_v1_dot_data__moniker__pb2.MonikerReadResult.SerializeToString,
            ),
            'ReadFromMoniker': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadFromMoniker,
                    request_deserializer=ni_dot_datamonikers_dot_v1_dot_data__moniker__pb2.Moniker.FromString,
                    response_serializer=ni_dot_datamonikers_dot_v1_dot_data__moniker__pb2.ReadFromMonikerResult.SerializeToString,
            ),
            'WriteToMoniker': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteToMoniker,
                    request_deserializer=ni_dot_datamonikers_dot_v1_dot_data__moniker__pb2.WriteToMonikerRequest.FromString,
                    response_serializer=ni_dot_datamonikers_dot_v1_dot_data__moniker__pb2.WriteToMonikerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ni.datamonikers.v1.MonikerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MonikerService(object):
    """Service for reading and writing data values using data monikers.

    Not all implementations implement all RPCs and clients should
    handle this gracefully.
    """

    @staticmethod
    def BeginSidebandStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ni.datamonikers.v1.MonikerService/BeginSidebandStream',
            ni_dot_datamonikers_dot_v1_dot_data__moniker__pb2.BeginMonikerSidebandStreamRequest.SerializeToString,
            ni_dot_datamonikers_dot_v1_dot_data__moniker__pb2.BeginMonikerSidebandStreamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamRead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ni.datamonikers.v1.MonikerService/StreamRead',
            ni_dot_datamonikers_dot_v1_dot_data__moniker__pb2.MonikerList.SerializeToString,
            ni_dot_datamonikers_dot_v1_dot_data__moniker__pb2.MonikerReadResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamWrite(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/ni.datamonikers.v1.MonikerService/StreamWrite',
            ni_dot_datamonikers_dot_v1_dot_data__moniker__pb2.MonikerWriteRequest.SerializeToString,
            ni_dot_datamonikers_dot_v1_dot_data__moniker__pb2.StreamWriteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamReadWrite(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/ni.datamonikers.v1.MonikerService/StreamReadWrite',
            ni_dot_datamonikers_dot_v1_dot_data__moniker__pb2.MonikerWriteRequest.SerializeToString,
            ni_dot_datamonikers_dot_v1_dot_data__moniker__pb2.MonikerReadResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadFromMoniker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ni.datamonikers.v1.MonikerService/ReadFromMoniker',
            ni_dot_datamonikers_dot_v1_dot_data__moniker__pb2.Moniker.SerializeToString,
            ni_dot_datamonikers_dot_v1_dot_data__moniker__pb2.ReadFromMonikerResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WriteToMoniker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ni.datamonikers.v1.MonikerService/WriteToMoniker',
            ni_dot_datamonikers_dot_v1_dot_data__moniker__pb2.WriteToMonikerRequest.SerializeToString,
            ni_dot_datamonikers_dot_v1_dot_data__moniker__pb2.WriteToMonikerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
