# .readthedocs.yml

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      - pip install poetry==2.1.4
    post_install:
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry -C packages/ni.datamonikers.client.v1.client install --only main,docs

sphinx:
  configuration: packages/ni.datamonikers.v1.client/docs/conf.py