name: Check Package

on:
  workflow_call:
    inputs:
      proto-basepath:
        description: 'The base path for proto files used for generation.'
        default: ''
        required: true
        type: string
      proto-subpath:
        description: 'The path to proto files relative to proto-base-path.'
        default: ''
        required: true
        type: string
      output-basepath:
        description: 'The base output path for codegened files.'
        default: ''
        required: true
        type: string
      output-format:
        description: 'The format for the generated stubs. Options are submodule and __.'
        default: ''
        required: true
        type: string
  workflow_dispatch:

jobs:
  check_codegen:
    name: Check codegen up-to-date
    runs-on: ubuntu-latest
    defaults:
      run:
        # Set the working-directory for all steps in this job.
        working-directory: ./tools/grpc_generator
    steps:
      - name: Check out repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: true
      - name: Set up Python
        uses: ni/python-actions/setup-python@5286c12d65d90b2ea738bd57d452dc4366497581 # v0.4.1
        id: setup-python
      - name: Set up Poetry
        uses: ni/python-actions/setup-poetry@5286c12d65d90b2ea738bd57d452dc4366497581 # v0.4.1
      - name: Check for lock changes
        run: poetry check --lock
      - name: Cache virtualenv
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: tools/grpc_generator/.venv
          key: grpc_generator-${{ runner.os }}-py${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('tools/grpc_generator/poetry.lock') }}
      - name: Install grpc_generator
        run: poetry install -v
      - name: Generate gRPC stubs
        run: |
          find ${{ inputs.output-basepath }} -name \*_pb2.py\* -o -name \*_pb2_grpc.py\* -delete
          poetry run grpc-generator --proto-basepath ${{ inputs.proto-basepath }} --proto-subpath ${{ inputs.proto-subpath }} --output-basepath ${{ inputs.output-basepath }} --output-format ${{ inputs.output-format }}
      - name: Check for out-of-date gRPC stubs
        run:  git diff --exit-code
      - name: Revert gRPC stubs
        run: |
          git clean ${{ inputs.output-basepath }}
          git restore ${{ inputs.output-basepath }}
