name: Check analyzers

on:
  workflow_call:
    inputs:
      package-name:
        description: 'The name of the package folder to check.'
        default: ''
        required: true
        type: string
      package-basepath:
        description: 'The base path of the package to check, relative to the repo root.'
        default: ''
        required: true
        type: string
      install-extras:
        description: 'A space-separated list of package extras to install.'
        default: ''
        required: false
        type: string

jobs:
  check_analyzers:
    name: Check analyzers for ${{ inputs.package-name }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]  # Temporarily disabled: macos-latest
        python-version: ['3.10', 3.14]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        # Set the working-directory for all steps in this job.
        working-directory: ${{ github.workspace }}/${{ inputs.package-basepath }}/${{ inputs.package-name }}
    steps:
      - name: Check out repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          submodules: true
      - name: Set up Python
        uses: ni/python-actions/setup-python@a2554c7e5680982d3355677b2290e48b60678744 # v0.8.0
        id: setup-python
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up Poetry
        uses: ni/python-actions/setup-poetry@a2554c7e5680982d3355677b2290e48b60678744 # v0.8.0
      - name: Analyze Python Project
        uses: ni/python-actions/analyze-project@a2554c7e5680982d3355677b2290e48b60678744 # v0.8.0
        with:
          project-directory: ${{ github.workspace }}/${{ inputs.package-basepath }}/${{ inputs.package-name }}
          install-args: "--extras '${{ inputs.install-extras }}'"
      - name: Bandit security checks
        run:  poetry run bandit -c pyproject.toml -r src/
