"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
---------------------------------------------------------------------
---------------------------------------------------------------------
"""

import builtins
import collections.abc
import google.protobuf.any_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _SidebandStrategy:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _SidebandStrategyEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SidebandStrategy.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UNKNOWN: _SidebandStrategy.ValueType  # 0
    """No strategy selected."""
    GRPC: _SidebandStrategy.ValueType  # 1
    """Standard gRPC transport."""
    SHARED_MEMORY: _SidebandStrategy.ValueType  # 2
    """Shared memory transport. Client and server must be on the same machine."""
    DOUBLE_BUFFERED_SHARED_MEMORY: _SidebandStrategy.ValueType  # 3
    """Same as SHARED_MEMORY except double buffered. This uses more memory but
    allows the client and server to read and write at the same time without
    blocking each other.
    """
    SOCKETS: _SidebandStrategy.ValueType  # 4
    """TCP Socket-based transport."""
    SOCKETS_LOW_LATENCY: _SidebandStrategy.ValueType  # 5
    """TCP Socket-based transport optimized for lower latency at the expense
    of higher CPU usage.
    """
    HYPERVISOR_SOCKETS: _SidebandStrategy.ValueType  # 6
    """Hypervisor-assisted socket transport. Not currently implemented."""
    RDMA: _SidebandStrategy.ValueType  # 7
    """RDMA-based transport. Requires that the network card on both the client
    and the server support RDMA.
    """
    RDMA_LOW_LATENCY: _SidebandStrategy.ValueType  # 8
    """RDMA transport optimized for lower latency at the expense of higher
    CPU usage.
    """

class SidebandStrategy(_SidebandStrategy, metaclass=_SidebandStrategyEnumTypeWrapper): ...

UNKNOWN: SidebandStrategy.ValueType  # 0
"""No strategy selected."""
GRPC: SidebandStrategy.ValueType  # 1
"""Standard gRPC transport."""
SHARED_MEMORY: SidebandStrategy.ValueType  # 2
"""Shared memory transport. Client and server must be on the same machine."""
DOUBLE_BUFFERED_SHARED_MEMORY: SidebandStrategy.ValueType  # 3
"""Same as SHARED_MEMORY except double buffered. This uses more memory but
allows the client and server to read and write at the same time without
blocking each other.
"""
SOCKETS: SidebandStrategy.ValueType  # 4
"""TCP Socket-based transport."""
SOCKETS_LOW_LATENCY: SidebandStrategy.ValueType  # 5
"""TCP Socket-based transport optimized for lower latency at the expense
of higher CPU usage.
"""
HYPERVISOR_SOCKETS: SidebandStrategy.ValueType  # 6
"""Hypervisor-assisted socket transport. Not currently implemented."""
RDMA: SidebandStrategy.ValueType  # 7
"""RDMA-based transport. Requires that the network card on both the client
and the server support RDMA.
"""
RDMA_LOW_LATENCY: SidebandStrategy.ValueType  # 8
"""RDMA transport optimized for lower latency at the expense of higher
CPU usage.
"""
global___SidebandStrategy = SidebandStrategy

@typing.final
class Moniker(google.protobuf.message.Message):
    """Identifier used to represent a data source from which data values can
    be read or written.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SERVICE_LOCATION_FIELD_NUMBER: builtins.int
    DATA_SOURCE_FIELD_NUMBER: builtins.int
    DATA_INSTANCE_FIELD_NUMBER: builtins.int
    service_location: builtins.str
    """Service location or endpoint identifier."""
    data_source: builtins.str
    """Logical data source name."""
    data_instance: builtins.int
    """Specific instance identifier within the data source."""
    def __init__(
        self,
        *,
        service_location: builtins.str = ...,
        data_source: builtins.str = ...,
        data_instance: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["data_instance", b"data_instance", "data_source", b"data_source", "service_location", b"service_location"]) -> None: ...

global___Moniker = Moniker

@typing.final
class MonikerValues(google.protobuf.message.Message):
    """Message which contains a batch of data values.

    For reads, values contains the returned data values for one or more
    data monikers. For writes, values contains the data values to be
    applied to one or more data monikers.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUES_FIELD_NUMBER: builtins.int
    @property
    def values(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.protobuf.any_pb2.Any]:
        """Data values carried as protobuf Any messages."""

    def __init__(
        self,
        *,
        values: collections.abc.Iterable[google.protobuf.any_pb2.Any] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["values", b"values"]) -> None: ...

global___MonikerValues = MonikerValues

@typing.final
class MonikerList(google.protobuf.message.Message):
    """Message which identifies the set of read and write monikers for a
    particular operation.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IS_INITIAL_WRITE_FIELD_NUMBER: builtins.int
    READ_MONIKERS_FIELD_NUMBER: builtins.int
    WRITE_MONIKERS_FIELD_NUMBER: builtins.int
    is_initial_write: builtins.bool
    """Deprecated. Preserved for backward compatibility."""
    @property
    def read_monikers(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Moniker]:
        """Monikers from which to read."""

    @property
    def write_monikers(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Moniker]:
        """Monikers to update with new data values."""

    def __init__(
        self,
        *,
        is_initial_write: builtins.bool = ...,
        read_monikers: collections.abc.Iterable[global___Moniker] | None = ...,
        write_monikers: collections.abc.Iterable[global___Moniker] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["is_initial_write", b"is_initial_write", "read_monikers", b"read_monikers", "write_monikers", b"write_monikers"]) -> None: ...

global___MonikerList = MonikerList

@typing.final
class BeginMonikerSidebandStreamRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STRATEGY_FIELD_NUMBER: builtins.int
    MONIKERS_FIELD_NUMBER: builtins.int
    strategy: global___SidebandStrategy.ValueType
    """The transport to use for the sideband communication channel."""
    @property
    def monikers(self) -> global___MonikerList:
        """Monikers participating in the sideband communication channel."""

    def __init__(
        self,
        *,
        strategy: global___SidebandStrategy.ValueType = ...,
        monikers: global___MonikerList | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["monikers", b"monikers"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["monikers", b"monikers", "strategy", b"strategy"]) -> None: ...

global___BeginMonikerSidebandStreamRequest = BeginMonikerSidebandStreamRequest

@typing.final
class BeginMonikerSidebandStreamResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STRATEGY_FIELD_NUMBER: builtins.int
    CONNECTION_URL_FIELD_NUMBER: builtins.int
    SIDEBAND_IDENTIFIER_FIELD_NUMBER: builtins.int
    BUFFER_SIZE_FIELD_NUMBER: builtins.int
    strategy: global___SidebandStrategy.ValueType
    """Selected transport used for the the sideband communication channel."""
    connection_url: builtins.str
    """Transport-specific URL or endpoint used to establish the sideband connection."""
    sideband_identifier: builtins.str
    """Identifier used to identify communication session within the transport."""
    buffer_size: builtins.int
    """The buffer size in bytes used for the sideband transport."""
    def __init__(
        self,
        *,
        strategy: global___SidebandStrategy.ValueType = ...,
        connection_url: builtins.str = ...,
        sideband_identifier: builtins.str = ...,
        buffer_size: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["buffer_size", b"buffer_size", "connection_url", b"connection_url", "sideband_identifier", b"sideband_identifier", "strategy", b"strategy"]) -> None: ...

global___BeginMonikerSidebandStreamResponse = BeginMonikerSidebandStreamResponse

@typing.final
class MonikerWriteRequest(google.protobuf.message.Message):
    """Request message used to perform streaming writes."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MONIKERS_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    @property
    def monikers(self) -> global___MonikerList:
        """Initial handshake message that declares the target monikers."""

    @property
    def data(self) -> global___MonikerValues:
        """Value payload for the established write session.

        This field should be set on all subsequent messages after the initial
        handshake message.
        """

    def __init__(
        self,
        *,
        monikers: global___MonikerList | None = ...,
        data: global___MonikerValues | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["data", b"data", "monikers", b"monikers", "write_data", b"write_data"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["data", b"data", "monikers", b"monikers", "write_data", b"write_data"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["write_data", b"write_data"]) -> typing.Literal["monikers", "data"] | None: ...

global___MonikerWriteRequest = MonikerWriteRequest

@typing.final
class MonikerReadResult(google.protobuf.message.Message):
    """Response message used to perform streaming reads."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DATA_FIELD_NUMBER: builtins.int
    @property
    def data(self) -> global___MonikerValues:
        """Data values returned from the read monikers."""

    def __init__(
        self,
        *,
        data: global___MonikerValues | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["data", b"data"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["data", b"data"]) -> None: ...

global___MonikerReadResult = MonikerReadResult

@typing.final
class StreamWriteResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___StreamWriteResponse = StreamWriteResponse

@typing.final
class ReadFromMonikerResult(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUE_FIELD_NUMBER: builtins.int
    @property
    def value(self) -> google.protobuf.any_pb2.Any:
        """Data value read from the moniker or empty if no value was available."""

    def __init__(
        self,
        *,
        value: google.protobuf.any_pb2.Any | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["value", b"value"]) -> None: ...

global___ReadFromMonikerResult = ReadFromMonikerResult

@typing.final
class WriteToMonikerRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MONIKER_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    @property
    def moniker(self) -> global___Moniker:
        """The data moniker to update."""

    @property
    def value(self) -> google.protobuf.any_pb2.Any:
        """The data value to write to the moniker."""

    def __init__(
        self,
        *,
        moniker: global___Moniker | None = ...,
        value: google.protobuf.any_pb2.Any | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["moniker", b"moniker", "value", b"value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["moniker", b"moniker", "value", b"value"]) -> None: ...

global___WriteToMonikerRequest = WriteToMonikerRequest

@typing.final
class WriteToMonikerResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___WriteToMonikerResponse = WriteToMonikerResponse
